"""swap name and date attributes between Workout and Exercise

Revision ID: 03c7739dde19
Revises: 22d0f5e99d07
Create Date: 2025-02-01 17:47:40.857215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c7739dde19'
down_revision = '22d0f5e99d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_exercise_name')
        batch_op.create_index(batch_op.f('ix_exercise_date'), ['date'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_workout_date')
        batch_op.create_index(batch_op.f('ix_workout_name'), ['name'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_workout_name'))
        batch_op.create_index('ix_workout_date', ['date'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_exercise_date'))
        batch_op.create_index('ix_exercise_name', ['name'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
