"""move exercise_type from Exercise to Workout

Revision ID: 06f50cb4022f
Revises: 03c7739dde19
Create Date: 2025-02-01 21:23:51.062263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f50cb4022f'
down_revision = '03c7739dde19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_exercise')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('exercise_type')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('exercise_type')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.VARCHAR(length=64), nullable=False))

    op.create_table('_alembic_tmp_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('distance', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
