"""remove unique constraint from cardio/machine models

Revision ID: 142d1cbc7715
Revises: d802e5083625
Create Date: 2025-01-14 17:33:55.848113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d1cbc7715'
down_revision = 'd802e5083625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardio_exercise', schema=None) as batch_op:
        batch_op.drop_index('ix_cardio_exercise_name')
        batch_op.create_index(batch_op.f('ix_cardio_exercise_name'), ['name'], unique=False)

    with op.batch_alter_table('machine_exercise', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_exercise_name')
        batch_op.create_index(batch_op.f('ix_machine_exercise_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_exercise_name'))
        batch_op.create_index('ix_machine_exercise_name', ['name'], unique=1)

    with op.batch_alter_table('cardio_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardio_exercise_name'))
        batch_op.create_index('ix_cardio_exercise_name', ['name'], unique=1)

    # ### end Alembic commands ###
