"""add nullable to reps/weight/distance

Revision ID: 22d0f5e99d07
Revises: 33cbe6e104de
Create Date: 2025-01-29 16:24:25.530127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d0f5e99d07'
down_revision = '33cbe6e104de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('distance',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
