"""add is_stale to Workout model

Revision ID: 2432b791d09a
Revises: acc00e029c64
Create Date: 2025-02-14 00:42:13.487956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2432b791d09a'
down_revision = 'acc00e029c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stale', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('is_stale')

    # ### end Alembic commands ###
