"""consolidate Exercise tables into one table

Revision ID: 33cbe6e104de
Revises: 142d1cbc7715
Create Date: 2025-01-29 16:13:07.715364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cbe6e104de'
down_revision = '142d1cbc7715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('exercise_type', sa.String(length=64), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_name'), ['name'], unique=False)

    op.create_table('workout_exercise',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id')
    )
    with op.batch_alter_table('cardio_exercise', schema=None) as batch_op:
        batch_op.drop_index('ix_cardio_exercise_name')

    op.drop_table('cardio_exercise')
    op.drop_table('workout_machine_exercise')
    with op.batch_alter_table('machine_exercise', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_exercise_name')

    op.drop_table('machine_exercise')
    op.drop_table('workout_cardio_exercise')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_cardio_exercise',
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('cardio_exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cardio_exercise_id'], ['cardio_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'cardio_exercise_id')
    )
    op.create_table('machine_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_exercise', schema=None) as batch_op:
        batch_op.create_index('ix_machine_exercise_name', ['name'], unique=False)

    op.create_table('workout_machine_exercise',
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('machine_exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['machine_exercise_id'], ['machine_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'machine_exercise_id')
    )
    op.create_table('cardio_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('distance', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cardio_exercise', schema=None) as batch_op:
        batch_op.create_index('ix_cardio_exercise_name', ['name'], unique=False)

    op.drop_table('workout_exercise')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_name'))

    op.drop_table('exercise')
    # ### end Alembic commands ###
