"""Added Workout association object and machine/cardio assoc tables

Revision ID: 3bed0a36109d
Revises: 8e9d7bacd1ef
Create Date: 2025-01-08 18:21:08.383633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bed0a36109d'
down_revision = '8e9d7bacd1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cardio_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardio_exercise_name'), ['name'], unique=True)

    op.create_table('machine_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_exercise_name'), ['name'], unique=True)

    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_user_id'), ['user_id'], unique=False)

    op.create_table('Cardio Workouts',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('cardio_exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardio_exercise_id'], ['cardio_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'cardio_exercise_id')
    )
    op.create_table('Machine Workouts',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('machine_exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_exercise_id'], ['machine_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'machine_exercise_id')
    )
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_date')
        batch_op.drop_index('ix_machine_name')
        batch_op.drop_index('ix_machine_user_id')

    op.drop_table('machine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.create_index('ix_machine_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_machine_name', ['name'], unique=1)
        batch_op.create_index('ix_machine_date', ['date'], unique=False)

    op.drop_table('Machine Workouts')
    op.drop_table('Cardio Workouts')
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_date'))

    op.drop_table('workout')
    with op.batch_alter_table('machine_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_exercise_name'))

    op.drop_table('machine_exercise')
    with op.batch_alter_table('cardio_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardio_exercise_name'))

    op.drop_table('cardio_exercise')
    # ### end Alembic commands ###
