"""renamed model Workouts to Machine

Revision ID: 8e9d7bacd1ef
Revises: 9ccef9612390
Create Date: 2025-01-08 09:18:37.089528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9d7bacd1ef'
down_revision = '9ccef9612390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_machine_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_date')
        batch_op.drop_index('ix_workout_name')
        batch_op.drop_index('ix_workout_user_id')

    op.drop_table('workout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.create_index('ix_workout_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_workout_name', ['name'], unique=1)
        batch_op.create_index('ix_workout_date', ['date'], unique=False)

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_user_id'))
        batch_op.drop_index(batch_op.f('ix_machine_name'))
        batch_op.drop_index(batch_op.f('ix_machine_date'))

    op.drop_table('machine')
    # ### end Alembic commands ###
