"""remove reps attribute from Exercise Model

Revision ID: acc00e029c64
Revises: 26edf191d8ff
Create Date: 2025-02-09 00:54:19.495312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc00e029c64'
down_revision = '26edf191d8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('reps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
