"""Added Workout association object and machine/cardio assoc tablesv2

Revision ID: d802e5083625
Revises: 3bed0a36109d
Create Date: 2025-01-08 18:40:46.512446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd802e5083625'
down_revision = '3bed0a36109d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_cardio_exercise',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('cardio_exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardio_exercise_id'], ['cardio_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'cardio_exercise_id')
    )
    op.create_table('workout_machine_exercise',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('machine_exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_exercise_id'], ['machine_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'machine_exercise_id')
    )
    op.drop_table('Cardio Workouts')
    op.drop_table('Machine Workouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Machine Workouts',
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('machine_exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['machine_exercise_id'], ['machine_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'machine_exercise_id')
    )
    op.create_table('Cardio Workouts',
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('cardio_exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cardio_exercise_id'], ['cardio_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'cardio_exercise_id')
    )
    op.drop_table('workout_machine_exercise')
    op.drop_table('workout_cardio_exercise')
    # ### end Alembic commands ###
